<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>SchemaError: unknown rule 'postid' for field 'schema' // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css" type="text/css">
    <!-- We need to make sure this has a favicon so that the debugger does not by
         accident trigger a request to /favicon.ico which might change the application
         state. -->
    <link rel="shortcut icon" href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>
    <script type="text/javascript" src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script type="text/javascript">
      var TRACEBACK = 140233732754640,
          CONSOLE_MODE = false,
          EVALEX = true,
          SECRET = "vMm7qWQAOLIstexjqoRc";
    </script>
  </head>
  <body>
    <div class="debugger">
<h1>cerberus.cerberus.SchemaError</h1>
<div class="detail">
  <p class="errormsg">SchemaError: unknown rule 'postid' for field 'schema'</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">
  
  <ul><li><div class="frame" id="frame-140233732754512">
  <h4>File <cite class="filename">"/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1820</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.make_response(self.handle_exception(e))</pre>
</div>

<li><div class="frame" id="frame-140233645299216">
  <h4>File <cite class="filename">"/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1403</em>,
      in <code class="function">handle_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-140233645298320">
  <h4>File <cite class="filename">"/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1817</em>,
      in <code class="function">wsgi_app</code></h4>
  <pre>response = self.full_dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-140233645299024">
  <h4>File <cite class="filename">"/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1477</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.handle_user_exception(e)</pre>
</div>

<li><div class="frame" id="frame-140233645298896">
  <h4>File <cite class="filename">"/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1381</em>,
      in <code class="function">handle_user_exception</code></h4>
  <pre>reraise(exc_type, exc_value, tb)</pre>
</div>

<li><div class="frame" id="frame-140233645297808">
  <h4>File <cite class="filename">"/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1475</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <pre>rv = self.dispatch_request()</pre>
</div>

<li><div class="frame" id="frame-140233645299472">
  <h4>File <cite class="filename">"/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1461</em>,
      in <code class="function">dispatch_request</code></h4>
  <pre>return self.view_functions[rule.endpoint](**req.view_args)</pre>
</div>

<li><div class="frame" id="frame-140233645299728">
  <h4>File <cite class="filename">"/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/eve/endpoints.py"</cite>,
      line <em class="line">54</em>,
      in <code class="function">collections_endpoint</code></h4>
  <pre>response = post(resource)</pre>
</div>

<li><div class="frame" id="frame-140233645298256">
  <h4>File <cite class="filename">"/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/eve/methods/common.py"</cite>,
      line <em class="line">237</em>,
      in <code class="function">rate_limited</code></h4>
  <pre>return f(*args, **kwargs)</pre>
</div>

<li><div class="frame" id="frame-140233645299664">
  <h4>File <cite class="filename">"/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/eve/auth.py"</cite>,
      line <em class="line">68</em>,
      in <code class="function">decorated</code></h4>
  <pre>return f(*args, **kwargs)</pre>
</div>

<li><div class="frame" id="frame-140233645298832">
  <h4>File <cite class="filename">"/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/eve/methods/common.py"</cite>,
      line <em class="line">808</em>,
      in <code class="function">decorated</code></h4>
  <pre>r = f(resource, **combined_args)</pre>
</div>

<li><div class="frame" id="frame-140233645298384">
  <h4>File <cite class="filename">"/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/eve/methods/post.py"</cite>,
      line <em class="line">40</em>,
      in <code class="function">post</code></h4>
  <pre>return post_internal(resource, payl, skip_validation=False)</pre>
</div>

<li><div class="frame" id="frame-140233645300432">
  <h4>File <cite class="filename">"/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/eve/methods/post.py"</cite>,
      line <em class="line">146</em>,
      in <code class="function">post_internal</code></h4>
  <pre>validator = app.validator(schema, resource)</pre>
</div>

<li><div class="frame" id="frame-140233645299856">
  <h4>File <cite class="filename">"/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/eve/io/mongo/validation.py"</cite>,
      line <em class="line">56</em>,
      in <code class="function">__init__</code></h4>
  <pre>super(Validator, self).__init__(schema)</pre>
</div>

<li><div class="frame" id="frame-140233645299600">
  <h4>File <cite class="filename">"/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/cerberus/cerberus.py"</cite>,
      line <em class="line">126</em>,
      in <code class="function">__init__</code></h4>
  <pre>self.validate_schema(schema)</pre>
</div>

<li><div class="frame" id="frame-140233645300880">
  <h4>File <cite class="filename">"/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/cerberus/cerberus.py"</cite>,
      line <em class="line">297</em>,
      in <code class="function">validate_schema</code></h4>
  <pre>self.validate_schema({'schema': value})</pre>
</div>

<li><div class="frame" id="frame-140233645298512">
  <h4>File <cite class="filename">"/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/cerberus/cerberus.py"</cite>,
      line <em class="line">310</em>,
      in <code class="function">validate_schema</code></h4>
  <pre>constraint, field))</pre>
</div>
</ul>
  <blockquote>SchemaError: unknown rule 'postid' for field 'schema'</blockquote>
</div>

<div class="plain">
  <form action="/?__debugger__=yes&amp;cmd=paste" method="post">
    <p>
      <input type="hidden" name="language" value="pytb">
      This is the Copy/Paste friendly version of the traceback.  <span
      class="pastemessage">You can also paste this traceback into
      a <a href="https://gist.github.com/">gist</a>:
      <input type="submit" value="create paste"></span>
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/eve/endpoints.py", line 54, in collections_endpoint
    response = post(resource)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/eve/methods/common.py", line 237, in rate_limited
    return f(*args, **kwargs)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/eve/auth.py", line 68, in decorated
    return f(*args, **kwargs)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/eve/methods/common.py", line 808, in decorated
    r = f(resource, **combined_args)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/eve/methods/post.py", line 40, in post
    return post_internal(resource, payl, skip_validation=False)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/eve/methods/post.py", line 146, in post_internal
    validator = app.validator(schema, resource)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/eve/io/mongo/validation.py", line 56, in __init__
    super(Validator, self).__init__(schema)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/cerberus/cerberus.py", line 126, in __init__
    self.validate_schema(schema)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/cerberus/cerberus.py", line 297, in validate_schema
    self.validate_schema({'schema': value})
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/cerberus/cerberus.py", line 310, in validate_schema
    constraint, field))
SchemaError: unknown rule 'postid' for field 'schema'</textarea>
  </form>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/eve/endpoints.py", line 54, in collections_endpoint
    response = post(resource)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/eve/methods/common.py", line 237, in rate_limited
    return f(*args, **kwargs)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/eve/auth.py", line 68, in decorated
    return f(*args, **kwargs)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/eve/methods/common.py", line 808, in decorated
    r = f(resource, **combined_args)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/eve/methods/post.py", line 40, in post
    return post_internal(resource, payl, skip_validation=False)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/eve/methods/post.py", line 146, in post_internal
    validator = app.validator(schema, resource)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/eve/io/mongo/validation.py", line 56, in __init__
    super(Validator, self).__init__(schema)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/cerberus/cerberus.py", line 126, in __init__
    self.validate_schema(schema)
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/cerberus/cerberus.py", line 297, in validate_schema
    self.validate_schema({'schema': value})
  File "/home/so1ashok_theweber_in/venv/venv/lib/python2.7/site-packages/cerberus/cerberus.py", line 310, in validate_schema
    constraint, field))
SchemaError: unknown rule 'postid' for field 'schema'

-->
